title: Liquid Reality
email: chris@die-schneider.net
description: This blog is about architecture and modularity
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.liquid-reality.de"
twitter_username: schneider_chris
github_username:  cschneider
linkedin_username: christian-schneider-99327157
show_excerpts: true
markdown: kramdown
theme: minima
#theme: type-on-strap
plugins:
  - jekyll-feed
